blueprint:
  name: Air Control - Sensor (P1)
  description: Air Control using Door Sensor and Helper Switch
  domain: automation
  input:
    virtual_switch:
      name: Virtual Switch
      description: Boolean input created by helper
      selector:
        entity:
          domain: input_boolean
    air_sensor:
      name: Binary Sensor
      description: Door sensor attach to AC
      selector:
        entity:
          domain: binary_sensor

mode: single
max_exceeded: slient

trigger:
  - platform: state
    entity_id:
      - !input air_sensor
condition:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: !input virtual_switch
            state: 'on'
          - condition: state
            entity_id: !input air_sensor
            state: 'off'
      - condition: and
        conditions:
          - condition: state
            entity_id: !input virtual_switch
            state: 'off'
          - condition: state
            entity_id: !input air_sensor
            state: 'on'
action:
  - service: input_boolean.toggle
    data: {}
    target:
      entity_id: !input virtual_switch
mode: single
