blueprint:
  name: Air Control - Sensor
  description: Air control using door sensor and helper switch (part 1)
  domain: automation
  input:
    air_sensor_entity:
      name: Binary Sensor
      selector:
        entity:
          domain: binary_sensor
    virtual_switch_entity:
      name: Virtual Switch
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: state
    entity_id:
      - !input air_sensor_entity
condition:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: !input virtual_switch_entity
            state: 'on'
          - condition: state
            entity_id: !input air_sensor_entity
            state: 'off'
      - condition: and
        conditions:
          - condition: state
            entity_id: !input virtual_switch_entity
            state: 'off'
          - condition: state
            entity_id: !input air_sensor_entity
            state: 'on'
action:
  - service: input_boolean.toggle
    data: {}
    target:
      entity_id: !input virtual_switch_entity

mode: single