blueprint:
  name: Air Control - Sensor
  description: Air control using door sensor and helper switch
  domain: automation
  input:
    virtual_switch:
      name: Virtual Switch
      selector:
        entity:
          domain: input_boolean
    air_sensor:
      name: Air Sensor
      selector:
        entity:
          domain: binary_sensor

mode: restart
max_exceeded: slient

trigger:
  platform: state
  entity_id: !input air_sensor
condition:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: !input virtual_switch
            state: "on"
          - condition: state
            entity_id: !input air_sensor
            state: "off"
      - condition: and
        conditions:
          - condition: state
            entity_id: !input virtual_switch
            state: "off"
          - condition: state
            entity_id: !input air_sensor
            state: "on"
action:
  - alias: "Toggle the virtual switch"
    service: input_boolean.toggle
    target: !input virtual_switch

